-- Active: 1766026092009@@127.0.0.1@25432@metastore@public
DO
$$
BEGIN
   IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'hive') THEN
      CREATE ROLE hive LOGIN PASSWORD 'hive';
   END IF;
END
$$;

GRANT ALL PRIVILEGES ON DATABASE metastore TO hive;

CREATE DATABASE hive;
GRANT ALL PRIVILEGES ON DATABASE hive TO hive;

